# Generated by Django 5.1.2 on 2024-10-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='quantity',
            new_name='purchase_quantity',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
