# Generated by Django 5.1.2 on 2024-10-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_profile_address_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferences',
            field=models.JSONField(blank=True, max_length=100),
        ),
    ]
