# Generated by Django 5.1.2 on 2024-10-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_profile_city_profile_postcode_profile_suburb'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
