# Generated by Django 5.1.2 on 2024-10-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_sale_custom_item_name_alter_item_stock_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='stock_quantity',
            new_name='remaining_quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='low_stock_treshold',
        ),
        migrations.AddField(
            model_name='item',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
