# Generated by Django 5.1.2 on 2024-11-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='remaining_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
